mybatis-flex/mybatis-flex

mybatis-flex-spring-boot-starter/pom.xml

`spring-boot-configuration-processor` and `spring-boot-autoconfigure-processor` should be optional.
see [configuration-metadata](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#appendix.configuration-metadata.annotation-processor.configuring).
```xml
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-configuration-processor</artifactId>
<optional>true</optional>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-autoconfigure-processor</artifactId>
<optional>true</optional>
</dependency>
```

Configuration processor and autoconfigure processor should be optional

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/DbType.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/DialectFactory.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/impl/DB2105Dialect.java

This pull request adds support for the DB2 10.5 version database. It includes a new dialect implementation, `DB2105Dialect`, which handles the specific pagination requirements of DB2 10.5. This allows developers to use the `row_number` window function for pagination instead of the `offset` keyword, which is not supported in DB2 10.5.
This change improves compatibility with DB2 10.5 and provides a more consistent experience for developers using MyBatisFlex with this version of DB2.

Add support for DB2 10.5 version

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/impl/DB2105Dialect.java

This pull request fixes an issue with the DB2 V10.5 dialect where the Nulls First|Nulls Last syntax is not supported. The issue is resolved by rewriting the syntax using the case when statement. This ensures compatibility with DB2 V10.5.

Fix DB2 V10.5 Nulls First|Nulls Last syntax

---

mybatis-flex-test/mybatis-flex-spring-boot-test/pom.xml
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/TestInfrastructure.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/AccountMapperTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/ActiveRecordTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/CombinedMapperTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/MyAccountMapperTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/OuterMapperTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/PatientMapperTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/QueryChainTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/UserMapperTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/service/ArticleServiceTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/service/FieldMappingTest.java
pom.xml

Hi, this PR aims to support #246 , using `TestContainers` to do Integration Test in `mybatis-flex-spring-boot-test`, it will start up a `MySQL` container when the test starts.

Test with TestContainers

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/table/TableInfoFactory.java

场景复现，有如下自定义typeHandler，需要在项目启动动态从配置中加载其属性aesKey的值
```java
@Slf4j
@Setter
@MappedJdbcTypes(value = {JdbcType.UNDEFINED, JdbcType.VARCHAR})
@MappedTypes(value = String.class)
public class AESTypeHandler extends StringTypeHandler {
private String aesKey;
@Override
public void setNonNullParameter(PreparedStatement ps, int i, String parameter, JdbcType jdbcType) throws SQLException {
String encryptedValue = AESUtils.encrypt(parameter, aesKey);
ps.setString(i, encryptedValue);
}
@Override
public String getNullableResult(ResultSet rs, String columnName) throws SQLException {
String encryptedValue = rs.getString(columnName);
return AESUtils.decrypt(encryptedValue, aesKey);
}
@Override
public String getNullableResult(ResultSet rs, int columnIndex) throws SQLException {
String encryptedValue = …
```

支持通过FlexConfiguration预注册的自定义typeHandler，同时解决需要带自定义初始化参数的问题

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/FlexGlobalConfig.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/table/TableInfo.java
mybatis-flex-core/src/test/java/com/mybatisflex/core/FlexGlobalConfigTest.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/common/ListenerTest.java

顶层接口定义如下：
```java
public interface IBaseEntity {
}
public interface IGeneralEntity extends IBaseEntity {
}
```
实体类定义：
```java
public class Dept implements IGeneralEntity {
}
```
全局配置：注册一个通用实体监听器
```java
FlexGlobalConfig.getDefaultConfig()
.registerUpdateListener(new CustomEntityListener(), IBaseEntity.class);
```
当使用 `IBaseEntity.class` 进行注册时，监听器将失效，`FlexGlobalConfig` 中对监听器和实体类的匹配逻辑有点问题
该 PR 直接使用 `class.isAssignableFrom( )` 进行匹配（见：`findSupportedListeners`），同时移除多段重复代码

修复实体类实现多层级的接口时监听器无法匹配问题

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/mybatis/Mappers.java

使用 Mappers 根据实体类获取对应 Mapper 并执行语法，
```
List<Patient> patients = Mappers.ofEntityClass(Patient.class).selectListByQuery(QueryWrapper.create());
```
**改造前异常输出格式**
```
2024-02-20T10:15:28.008+08:00 ERROR 5592 --- [sky-demo-service] [nio-8088-exec-8] c.z.s.w.r.e.h.GlobalExceptionHandler     : ORA-00904: "NAME": 标识符无效
java.lang.reflect.UndeclaredThrowableException: null
at jdk.proxy2/jdk.proxy2.$Proxy110.selectListByQuery(Unknown Source) ~[na:na]
at com.xxx.demo.controller.TmpController.test(TmpController.java:182) ~[classes/:na]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableH …
```

修复使用Mappers执行语法时, 异常未被精确抛出问题

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/AbstractRelation.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/ManyToMany.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/ManyToOne.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/OneToMany.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/OneToOne.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/RelationManager.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/ToManyRelation.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/relation/ToOneRelation.java

将相关功能默认访问级别调整为 `public`，便于第三方框架功能扩展

feat: 调整关联查询相关功能模块访问级别

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/table/TableInfo.java

在手动实现自定义动态查询时，暴露该方法，利于代码复用。      
例如我目前实现通用查询的时候，由于传入的类型为`Class<?>`，此时手动实现map查询结果，映射至`Class<?>`实体类时，可根据此方法返回的映射关系手动赋值。

提供实体类与数据库字段字段映射内容

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/util/ClassUtil.java

通过ModifyAttrsRecordProxyFactory.get方法调用ClassUtil.newInstance时，会给实体类创建一个代理类作为参数，在实体类需要静态方法创建实例的时候，判断clazz == m.getReturnType()时就为false，所以加了个判断如果是代理类，就获取其父类

 fix: ClassUtil.newInstance无法生成实例问题修复 https://github.com/mybatis-flex/mybatis-flex/issues/259

---

mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/dialect/IDialect.java
mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/dialect/impl/PostgreSQLJdbcDialect.java

添加了 PostgreSQLJdbcDialect 类的实现，以支持 Postgres 数据库的代码生成功能。
主要避免关键词导致的生成失败比如 user

feat(dialect): 添加 PostgreSQL 方言实现

---

mybatis-flex-processor/src/main/java/com/mybatisflex/processor/config/MybatisFlexConfig.java

该PR增强了 `mybatis-flex.config` 的配置方式，目前官方文档支持的配置方式：
```
在项目的根目录 （ pom.xml 所在的目录）下创建 `mybatis-flex.config` 配置文件。
```
在企业项目开发中，通常会封装一个统一的 ORM 包，希望可以通过统一的框架包来管理默认的配置，而无需在各个项目中都配置一遍（几十个项目全部配置一遍，后续调整非常麻烦）
该 PR 支持在框架层面的 JAR 包 `resources` 目录下添加 `mybatis-flex.config` （/src/main/resources/mybatis-flex.config）配置文件，所有依赖的子项目会自动读取到该配置。

feat: APT 支持从 Resources 目录进行配置

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/util/MapperUtil.java

错误的SQL语法执行分页时，count 优化后变成正常的语法被执行
```
select *
from "test"."order" as "t1"
having sum("t1"."total_cost") >= 10
```
上面的语法在不分页情况下将抛出异常（因为 having 必须配合 group by 使用）
```
ERROR: column "t1.total_cost" must appear in the GROUP BY clause or be used in an aggregate function
```
但是在分页时触发了 Count 语法优化逻辑，优化后的语法如下：
```
select count(*) as "total"
from "meta"."scm_drug_purchase_master" as "t1"
having sum("t1"."purchase_total_cost") >= 10
```
此时数据库不会抛出异常，被当做是一个正常的语法执行了
如果 SQL 语法本身就是错误的，那么分页语法应该不做优化，直接使用 select count(*) from ( 原始SQL ) 执行

fix: 修复分页包含 having 语句时，语法依然被优化问题

---

docs/zh/base/service.md
mybatis-flex-core/src/main/java/com/mybatisflex/core/service/IService.java

原始updateBatch方法默认忽略实体类null数值的字段，导致该方法在某些场景（比如数据同步）下不可用。
现添加可配置化，使updateBatch适配更多场景。

feat(mybatis-flex-core): 增加updateBatch方法是否忽略null字段的可配置性

---

docs/zh/others/apt.md
mybatis-flex-processor/src/main/java/com/mybatisflex/processor/MybatisFlexProcessor.java
mybatis-flex-processor/src/main/java/com/mybatisflex/processor/builder/ContentBuilder.java
mybatis-flex-processor/src/main/java/com/mybatisflex/processor/config/ConfigurationKey.java
mybatis-flex-processor/src/main/java/com/mybatisflex/processor/util/StrUtil.java

Link: https://github.com/mybatis-flex/mybatis-flex/issues/388
1. 增加processor.tableDef.package配置
2. 支持在APT中通过表达式选择package层级
支持以下配置项
```
processor.allInTables.package
processor.mapper.package
processor.tableDef.package
```
将`${entityPackage}`替换为实际实体包名, 表达式中如果存在一个`.parent`则缩减包名末尾的一位。
示例：`entityClass = com. test1.test2`
1. 对于`packageStr = ${entityPackage}`处理结果为 `com.test1.test2`
2. 对于`packageStr = ${entityPackage. parent}`处理结果为 `com.test1`
6. 对于`packageStr = ${entityPackage. parent}.customize`处理结果为 `com.test1.customize`

feat: 支持在APT中通过表达式选择package层级

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/FlexGlobalConfig.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/mybatis/FlexDefaultResultSetHandler.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/mybatis/UnMappedColumnHandler.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/java/com/mybatisflex/test/MyConfigurationCustomizer.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/java/com/mybatisflex/test/model/UnmappedBaseEntity.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/java/com/mybatisflex/test/model/UnmappedUser.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/java/com/mybatisflex/test/unmapped/MyUnMappedColumnHandler.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/resources/unmapped_user.sql
mybatis-flex-test/mybatis-flex-spring-boot-test/src/test/java/com/mybatisflex/test/mapper/UnmappedUserMapperTest.java

1. 对一些自定义查询时，比如as，as 的字段名在实体类中没有，但是实际需要以另一种方式获取；
2. 对于 数据库中有的字段，但是实体类中未定义的特殊字段，进行自定义处理；
3. 同名字段 在不同源中获取时，以不同名称获取，给予自定义操作。
`QueryWrapper queryWrapper = QueryWrapper.create()
.select(QueryMethods.column(Example::getId),
QueryMethods.column(Example::getExampleName),
QueryMethods.column(Example::getExampleName).as("name_test")));
List<JamExample> aclineList = exampleMapper.selectListByQuery(queryWrapper);`

增加未匹配列的自定义处理拓展接口

---

mybatis-flex-spring-boot3-starter/pom.xml

解决：[https://github.com/mybatis-flex/mybatis-flex/issues/336](https://github.com/mybatis-flex/mybatis-flex/issues/336)，详情见issue评论

chore: mybatis-spring升级同步升级mybatis依赖版本为3.5.16,解决issue：https://github.com/mybatis-flex/mybatis-flex/issues/336

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/handler/CompositeEnumTypeHandler.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/handler/FlexEnumTypeHandler.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/util/ClassUtil.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/util/EnumWrapper.java
mybatis-flex-test/mybatis-flex-native-test/src/main/java/com/mybatisflex/test/IBaseEnum.java
mybatis-flex-test/mybatis-flex-native-test/src/main/java/com/mybatisflex/test/SexEnum.java

修复 #377 仅在接口的方法上使用@EnumValue在[CompositeEnumTypeHandler.java](https://github.com/mybatis-flex/mybatis-flex/blob/main/mybatis-flex-core/src/main/java/com/mybatisflex/core/handler/CompositeEnumTypeHandler.java#L42) 
```java
List<Method> enumDbValueMethods = ClassUtil.getAllMethods(enumClass, m -> m.getAnnotation(EnumValue.class) != null);
```
无法获取到注解信息导致使用的TypeHandler委托为EnumTypeHandler而非FlexEnumTypeHandler

fix: 修复@EnumValue应用在接口方法上失效

---

mybatis-flex-spring/src/main/java/com/mybatisflex/spring/service/impl/ServiceImpl.java

原实现返回BaseMapper<T>，仅仅包含BaseMapper的方法实际应该是该Mapper接口实际的类型，不然就需要在业务Service接口中重写getMapper() 使其返回具体的Mapper类型
```java
//  修改前
@Override
public BaseMapper<T> getMapper() {
return mapper;
}
//  修改后
@Override
public M getMapper() {
return mapper;
}
```

feat: 为Spring的ServiceImpl#getMapper返回具体的约束泛型类型

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/datasource/FlexDataSource.java
mybatis-flex-spring/src/main/java/com/mybatisflex/spring/FlexSpringTransaction.java
mybatis-flex-spring/src/main/java/com/mybatisflex/spring/FlexTransactionManager.java
mybatis-flex-spring/src/main/java/com/mybatisflex/spring/TransactionDefinitionManager.java
mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/java/com/mybatisflex/test/service/AccountService.java

关联issue [issue-418](https://github.com/mybatis-flex/mybatis-flex/issues/418)
初步判断是FlexTransactionManager实现的TransactionObject对于Spring事务的支持还不够完整，提供TransactionDefinitionManager实现对事务超时时间的修复和检查，可能会对多数据源等功能带来不可预测的问题
@yangfuhai @Suomm

fix: 修复事务超时时间问题 & 提供更完善的Spring事务定义上下文

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/MybatisFlexBootstrap.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/mybatis/Mappers.java

修正多 MybatisFlexBootstrap 实例时调用 MybatisFlexBootstrap.getMapper(Class<T> mapperClass) 方法只能获取最后的实例的 mapper
Fixed the problem that when calling MybatisFlexBootstrap.getMapper(Class<T> mapperClass) method with multiple MybatisFlexBootstrap instances, only the mapper of the last instance can be obtained.

multiple MybatisFlexBootstrap instances

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/FlexGlobalConfig.java

修正创建多个 MybatisFlexBootstrap 实例时，FlexGlobalConfig.getConfig(environmentId) 获取的 config 永远是 defaultConfig。
When creating multiple MybatisFlexBootstrap instances, the config obtained by FlexGlobalConfig.getConfig(environmentId) is always defaultConfig.

修正创建多个 MybatisFlexBootstrap 实例时，FlexGlobalConfig 存储的 globalConfigs 实例都是 defaultConfig 对象。

---

docs/zh/others/codegen.md
mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/config/GlobalConfig.java

修复 Codegen GlobalConfig 类缺少 setEntityWithBaseClassEnable 函数问题
原来只能这样设置：
```java
globalConfig.getEntityConfig().setWithBaseClassEnable(true);
```
现在可以直接
```java
globalConfig.setEntityWithBaseClassEnable(true);
```

fix: 修复 Codegen GlobalConfig 类缺少 setEntityWithBaseClassEnable 函数问题

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/constant/SqlConsts.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/impl/CommonsDialectImpl.java
mybatis-flex-core/src/test/java/com/mybatisflex/coretest/QueryWrapperTest.java

[Issue-491: ](https://github.com/mybatis-flex/mybatis-flex/issues/491)
1. buildSelectSql方法，queryTables为空时，不拼接FROM关键词
2. wrap方法，如果keyword是"DUAL"关键词，直接输出原始内容

!491 fix: QueryWrapper无法支持常量查询

---

mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/IDialect.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/impl/CommonsDialectImpl.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/query/OperatorSelectCondition.java
mybatis-flex-core/src/test/java/com/mybatisflex/coretest/AccountSqlTester.java

#442 
项目中遇到了类似的问题，扩展 buildSelectSql() 实现别名传递
子查询的别名是不是也可以这样处理？

fix: exists 条件中的表别名和父查询保持一致

---

mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/config/GlobalConfig.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/BaseMapper.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/query/QueryMethods.java
mybatis-flex-core/src/main/java/com/mybatisflex/core/service/IService.java

对于`BaseMapper`、`IService`这几个类启用代码折抵支持，目前官方已经进行了分组，但没有使用代码折叠。
添加后代码效果：

feat: 对于用户常用类，启用代码折叠支持
