mybatis-flex/mybatis-flex

mybatis-flex-core/src/main/java/com/mybatisflex/core/FlexConsts.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/IDialect.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/impl/CommonsDialectImpl.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/provider/ProviderUtil.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/provider/RowSqlProvider.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/row/Db.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/row/RowMapper.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/row/RowMapperInvoker.java, mybatis-flex-test/mybatis-flex-native-test/src/main/java/com/mybatisflex/test/DbTestStarter.java, mybatis-flex-test/mybatis-flex-native-test/src/main/java/com/mybatisflex/test/MultiDataSourceTester.java, mybatis-flex-test/mybatis-flex-native-test/src/main/java/com/mybatisflex/test/RowTestStarter.java, mybatis-flex-test/mybatis-flex-spring-boot-test/src/main/java/com/mybatisflex/test/controller/AccountController.java, mybatis-flex-test/mybatis-flex-spring-test/src/test/java/com/mybatisflex/test/AccountTest.java
=> fixed:  Db+Row supports Schema。

mybatis-flex-core/src/main/java/com/mybatisflex/core/query/QueryColumn.java, mybatis-flex-spring-boot-starter/pom.xml
1. QueryColumn 添加一个含QueryTable的构造器
2. 升级druid 1.2.17->1.2.18
=> QueryColumn 添加一个含QueryTable的构造器

mybatis-flex-core/src/main/java/com/mybatisflex/core/keygen/CustomKeyGenerator.java
=> object is not an instance of declaring class

docs/zh/base/chain.md
=> docs: update docs/zh/base/chain.md

docs/zh/others/codegen.md, mybatis-flex-codegen/pom.xml, mybatis-flex-core/pom.xml, mybatis-flex-test/mybatis-flex-native-test/pom.xml, mybatis-flex-test/mybatis-flex-spring-boot-test/pom.xml, mybatis-flex-test/mybatis-flex-spring-cloud-test/pom.xml, pom.xml
fix maven warn.
[WARNING] The artifact mysql:mysql-connector-java:jar:8.0.33 has been relocated to com.mysql:mysql-connector-j:jar:8.0.33
[WARNING] The artifact org.hibernate:hibernate-validator:jar:7.0.5.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:7.0.5.Final
=> fix: Maven [WARNING] The artifact xxx has been relocated to.

docs/zh/base/chain.md
=> docs: fix typo in chain.md

mybatis-flex-core/src/main/java/com/mybatisflex/core/query/BaseQueryWrapper.java
=> feat(code): BaseQueryWrapper add clear() method

mybatis-flex-test/mybatis-flex-spring-test/src/main/java/com/mybatisflex/test/mapper/TbClassMapper.java, mybatis-flex-test/mybatis-flex-spring-test/src/main/java/com/mybatisflex/test/model/TbClass.java, mybatis-flex-test/mybatis-flex-spring-test/src/main/resources/data.sql, mybatis-flex-test/mybatis-flex-spring-test/src/main/resources/schema.sql, mybatis-flex-test/mybatis-flex-spring-test/src/test/java/com/mybatisflex/test/issue113/Issue113Test.java, mybatis-flex-test/mybatis-flex-spring-test/src/test/java/com/mybatisflex/test/issue113/def/TClassTableDef.java, mybatis-flex-test/mybatis-flex-spring-test/src/test/java/com/mybatisflex/test/issue113/def/TUserTableDef.java
#113 add unit test
please refer to modules mybatis-flex-spring-test (com.mybatisflex.test.issue113.Issue113Test)
=> test: add unit test for issue_113

mybatis-flex-core/src/main/java/com/mybatisflex/core/field/FieldQueryManager.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/util/DateUtil.java
=> feat: optimize

mybatis-flex-core/src/main/java/com/mybatisflex/core/util/LambdaUtil.java
当osgi环境下mybatis-flex与应用代码不在同一个bundle包中，会导致类找不到。需要获取到具体应用bundle包的classloader进行类加载
=> 修复OSGI环境ClassLoader获取不到类

mybatis-flex-core/src/main/java/com/mybatisflex/core/query/OperatorQueryCondition.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/query/OperatorSelectCondition.java
OperatorQueryCondition\OperatorSelectCondition::getValue缺少对effective检查
=> fix: OperatorQueryCondition\OperatorSelectCondition::getValue缺少对effective检查

docs/zh/base/querywrapper.md
pr一个QueryMethods使用文档的细节， where内可直接对列进行运算。
https://github.com/mybatis-flex/mybatis-flex/issues/173
=> feat:增加QueryMethods使用

mybatis-flex-core/src/main/java/com/mybatisflex/core/table/TableInfoFactory.java
使mapper可以支持多重继承、多层继承、多参数泛型继承等场景
=> 更好的getEntityClass实现

mybatis-flex-annotation/src/main/java/com/mybatisflex/annotation/AbstractInsertListener.java, mybatis-flex-annotation/src/main/java/com/mybatisflex/annotation/AbstractUpdateListener.java
=> refactor: 自动判断类型，省略子类实现

mybatis-flex-core/src/main/java/com/mybatisflex/core/audit/AuditManager.java
fix:修复SQL审计queryCount无法正确反映数据库修改行数的问题
=> fix:SQL审计正确返回变更行数

mybatis-flex-solon-plugin/src/main/java/com/mybatisflex/solon/service/impl/ServiceImpl.java
```java
class Person {}
interface PersonMapper extends BaseMapper<Person> {}
interface PersonManager extends IService<Person> {}
class PersonManagerImpl extends ServiceImpl<PersonMapper, Person> implements PersonManager {
void f() {
// No need to convert
TokenMapper mapper = this.getMapper();
}
}
```
=> feat(*): 调整ServiceImpl#getMapper返回Mapper类型特化

mybatis-flex-core/src/main/java/com/mybatisflex/core/query/QueryCondition.java
修复前：
修复后：
测试语句:
`QueryWrapper queryWrapper = QueryWrapper.create()
.select(USER.USER_ID, USER.USER_NAME, ROLE.ALL_COLUMNS)
.from(USER.as("u"))
.leftJoin(USER_ROLE).as("ur").on(USER_ROLE.USER_ID.eq(USER.USER_ID))
.leftJoin(ROLE).as("r").on(USER_ROLE.ROLE_ID.eq(ROLE.ROLE_ID))
.where(QueryMethods.not(Role::getRoleKey).eq("vip"));
System.err.println(queryWrapper.toSQL());
Page<UserVO> page = new Page<>();
page.setOptimizeCountQuery(true);
int pageNumber = 0;
do {
page = userMapper.paginateAs(page, queryWrapper, UserVO.class);
System.err.println(page);
page.setPageNumber(page.getPageNumber() + 1);
} while (page.hasNext());`
=> fix https://github.com/mybatis-flex/mybatis-flex/issues/307

changes.md, mybatis-flex-core/src/main/java/com/mybatisflex/core/FlexGlobalConfig.java
=> fix: 静态引用写错修改

docs/zh/others/codegen.md, mybatis-flex-codegen/src/main/resources/templates/enjoy/controller-Solon.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/controller.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/entity.kotlin.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/entityOrBase.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/entityWithBase.kotlin.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/entityWithBase.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/mapper.kotlin.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/mapper.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/package-info.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/service.kotlin.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/service.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/serviceImpl-Solon.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/serviceImpl.kotlin.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/serviceImpl.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/tableDef.tpl
JavadocConfig setAuthor 和 setSince 方法传入空字符串时，不添加注释 `@author`, `@since` 部分
related issue: https://github.com/mybatis-flex/mybatis-flex/issues/487
=> feat: JavadocConfig setAuthor 和 setSince 方法传入空字符串时，不添加注释 @author, @since 部分

mybatis-flex-codegen/src/main/resources/templates/enjoy/entityWithBase.tpl
entityWithBase.tpl 文件注解间多了一个换行
=> chore: entityWithBase.tpl 文件注解间多了一个换行

docs/zh/others/codegen.md, mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/config/EntityConfig.java, mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/config/GlobalConfig.java, mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/generator/impl/EntityGenerator.java
添加 setEntityBaseOverwriteEnable(boolean) 方法
=> feat: Codegen 生成 entity base 时支持设置是否覆盖已有文件

mybatis-flex-test/mybatis-flex-native-test/src/test/java/com/mybatisflex/test/AccountNativeTest.java
[pr-494](https://github.com/mybatis-flex/mybatis-flex/pull/494)
=> fix: 修复pr-494导致单元测试不通过问题

mybatis-flex-core/src/main/java/com/mybatisflex/core/keygen/MultiEntityKeyGenerator.java
=> fix:批量插入传set报错问题

docs/zh/others/codegen.md, mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/config/EntityConfig.java, mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/config/GlobalConfig.java, mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/generator/impl/EntityGenerator.java, mybatis-flex-codegen/src/main/resources/templates/enjoy/entityOrBase.tpl, mybatis-flex-codegen/src/main/resources/templates/enjoy/entityWithBase.tpl
related issue: https://github.com/mybatis-flex/mybatis-flex/issues/496
通过配置是否生成 lombok 注解 `@NoArgsConstructor`, `@AllArgsConstructor` 以解决 issue: #496 问题
=> feat: 支持配置 entity 类 lombok 注解生成 (`@NoArgsConstructor`, `@AllArgsConstructor`)

mybatis-flex-codegen/src/main/java/com/mybatisflex/codegen/entity/Column.java
- 例如`java.util.Optional<java.time.LocalDateTime>`这种类型
=> feat(Column): 支持带有范型的类型

mybatis-flex-core/src/main/java/com/mybatisflex/core/datasource/FlexDataSource.java
=> 修复Optional包依赖问题

mybatis-flex-spring/pom.xml
解决 #571 
BatchAutoConfiguration会提前加载DataSource，导致后置处理器失效
=> fix: spring-batch更改为optional

mybatis-flex-core/src/main/java/com/mybatisflex/core/constant/FuncName.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/DbType.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/dialect/DbTypeUtil.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/query/CastQueryColumn.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/query/QueryColumn.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/query/QueryMethods.java
- 在 FuncName 中添加 STRING_AGG 和 LISTAGG 函数
- 在 DbType 中添加方法判断数据库类型是否支持 MySQL、Oracle 或 PostgreSQL
- 在 DbTypeUtil 中添加获取当前数据库类型的方法
- 在 QueryMethods 中添加 STRING_AGG 和 LISTAGG聚合函数的支持
=> feat: 增加STRING_AGG、LISTAGG、CAST函数支持

mybatis-flex-codegen/pom.xml, mybatis-flex-core/pom.xml, mybatis-flex-core/src/main/java/com/mybatisflex/core/audit/AuditManager.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/audit/AuditMessage.java, mybatis-flex-core/src/main/java/com/mybatisflex/core/mybatis/FlexStatementHandler.java, mybatis-flex-dependencies/pom.xml, mybatis-flex-loveqq-starter/pom.xml, mybatis-flex-processor/pom.xml, mybatis-flex-solon-plugin/pom.xml, mybatis-flex-spring-boot-starter/pom.xml, mybatis-flex-spring-boot3-starter/pom.xml, mybatis-flex-spring/pom.xml, mybatis-flex-test/mybatis-flex-loveqq-test/pom.xml, mybatis-flex-test/mybatis-flex-native-test/pom.xml, mybatis-flex-test/mybatis-flex-seata-test/pom.xml, mybatis-flex-test/mybatis-flex-solon-test/pom.xml, mybatis-flex-test/mybatis-flex-spring-boot-test/pom.xml, mybatis-flex-test/mybatis-flex-spring-cloud-test/pom.xml, mybatis-flex-test/mybatis-flex-spring-test/pom.xml, mybatis-flex-test/mybatis-flex-spring-test/src/main/java/com/mybatisflex/test/mapper/AccountMapper.java, mybatis-flex-test/mybatis-flex-spring-test/src/test/java/com/mybatisflex/test/AuditTest.java, mybatis-flex-test/pom.xml, pom.xml
* 使用`revision`统一管理版本后，模块间依赖的版本应该用`project.version`
* `AuditMessage`增加`stmtId`属性，可以通过该字段进行过滤
=> feat/audit: 审计功能优化
